version: '3.4'

services:
  grapghql:
    container_name: grapghql
    image: gayankanishka/graphql-clean-architecture
    build:
      context: .
      dockerfile: src/GraphQL/Dockerfile
    ports:
      - '5000:5000'
      - '5001:5001'
    restart: on-failure
